name: "[PRODUCTION] [PYPI] Publish"
permissions:
  id-token: write
  contents: write
on:
  workflow_dispatch:

jobs:
  call_build_and_publish_workflow:
    uses: ./.github/workflows/reusable-build-and-publish.yml
    with:
      publish_target_type: "pypi"
    secrets:
      ONE_PASSWORD_TOKEN: ${{ secrets.ONE_PASSWORD_TOKEN }}
