name: "[STAGING] [JFROG] Publish"
permissions:
  id-token: write
  contents: write
on:
  workflow_dispatch:

jobs:
  call_build_and_publish_workflow:
    uses: ./.github/workflows/reusable-build-and-publish.yml
    with:
      publish_target_type: "jfrog"
      jfrog_repository_url: "https://thestage.jfrog.io/artifactory/api/pypi/pypi-thestage-ai-staging"
      jfrog_username: "v.avinkin@thestage.ai"
    secrets:
      ONE_PASSWORD_TOKEN: ${{ secrets.ONE_PASSWORD_TOKEN }}
